//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace whos_bad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int RegistroId { get; set; }
        public string Contexto { get; set; }
        public string Atitude { get; set; }
        public string Sentimento { get; set; }
        public string Humor { get; set; }
        public System.DateTime Data { get; set; }
        public string Pensamento { get; set; }
        public int FKUserId { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
