//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace whos_bad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registro()
        {
            this.Feedback = new HashSet<Feedback>();
        }
    
        public int RegistroId { get; set; }
        public string Contexto { get; set; }
        public string Atitude { get; set; }
        public int FKSentimentoId { get; set; }
        public int FKHumorId { get; set; }
        public int IntensidadeDoSentimento { get; set; }
        public System.DateTime Data { get; set; }
        public string Pensamento { get; set; }
        public int FKUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedback { get; set; }
        public virtual Humor Humor { get; set; }
        public virtual Sentimento Sentimento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
