//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace whos_bad.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class whosBadDBEntities : DbContext
    {
        public whosBadDBEntities()
            : base("name=whosBadDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comportamento> Comportamento { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<Humor> Humor { get; set; }
        public virtual DbSet<Registro> Registro { get; set; }
        public virtual DbSet<Sentimento> Sentimento { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
